### ISSUE TITLE
Error 3 While Using Bridge - Sent too much, was not able to type in new amount without resetting form

### ISSUE THREAD

**Issue by Dieth22** [BirthdayResearch/quantum-app#1]
#### What happened:
Hi, 

1)I filled out the form to transfer 3.87 ETH from Defichain to ETH.
2) I accidently filled out ammount as All on defichain for my eth transfer and sent 3.87387 instead of 3.87
3) When i went to verify the transfer it gave me error 3 which says:

### Error Code 3

- **Error Message:** BalanceNotMatched
- **Description:** The balance in the wallet's address is not equal to the amount filled in the form.
- **Solution:** Please make sure you transfer the exact amount to complete the transaction.

So i tried to go back and it wouldnt let me without starting a new transaction.

4) I started a new transaction and typed in 3.87387 and it gave me a new send to DFI address, and when i clicked verify it said error 4... but im guessing because i didn't send the eth to the new address i sent it to df1qg080zr77vd7vmhevqm3f9jqp03jylh87u0rsa7 

SO i do not know what I am suppose to do now there is no way for. me to transfer the exact ammount because I had to reset the form to try it.

#### What you expected to happen:

I expected it to just send me the extra amount minus the fee

#### How to reproduce it (as minimally and precisely as possible):
Send more eth than you type in the form

#### Anything else we need to know?:
I still have not received my eth, can you send to my eth address or send it back to my Defichain wallet?

If you need addresses I put them in google form

**Comment by thedoublejay** [comment]
Sent the excess funds back to your refund address. You can try again.

**Comment by Dieth22** [comment]
I can't because I exited out of the transaction to try to type in the
correct amount. Now everytime I try to redo the transaction it gives me a
new address (not the original one I sent it to)
