### ISSUE TITLE
Claim Error

### ISSUE THREAD

**Issue by ms-01** [BirthdayResearch/quantum-app#11]
#### What happened:
I want transfer DFI from Defichain to Ethereum. After successfull step 3 i've became a Claim Error After successfull validate.The transactionID wasn't found in the etherscan explorer. 

#### What you expected to happen:
That the DFI Token transfer to my Metamask after claiming.

#### Anything else we need to know?:
Transaction ID Defichain: 1ea1a30440c03e8ab690601a67bea7c22c126b51e2e36916c036f179275287

Destination address: df1qgmgmeevcw38st2f73hqnvqzcshn5uuyf0ry6

**Comment by lykalabrada** [comment]
Hi @ms-01, your claim is valid until 6:20 AM on October 31, 2023. Please continue to attempt claim until then. We will proceed with processing your refund once the claim has expired

**Comment by ms-01** [comment]
Thanks for the feedback. I tried again and now I get error 3. Various transactions can be seen on the address df1qgmgmeevcw38st2f73hqnvqzcshn5uuyf0ry6w2. Can you send the funds back to my address?

**Comment by ms-01** [comment]
Unfortunately, claiming didn't work.

**Comment by ms-01** [comment]
@lykalabrada 

Is there anything else I can do? How long will the reversal process take? I would be grateful for a short response. Best regards

**Comment by ms-01** [comment]
@thedoublejay Can you perhabs help? Thank you for that!
