### ISSUE TITLE
Chrome froze, USDT transferred and ETH Tx ID received, but funds not bridged to Defichain: USDT 10400; Recovery impossible

### ISSUE THREAD

**Issue by Defianer** [BirthdayResearch/quantum-app#13]
#### What happened:
While transferring my USDT from ETH to Defichain, I confirmed the Tx on Metamask, but my Chrome browser froze with a "Please confirm the Tx on Metamask" message.
ETH Tx was completed, Tx ID 0x5cfdb49a5303b7f71f9248a00b49b3bd0f353098a21b9d0f3ab930e812036f06.
Recovery not possible, error message reads "Invalid transaction hash. Please only enter instant transaction hash."
The Tx ID is valid, but not recognized by the bridge.

#### What you expected to happen:
Recovery should work with Tx ID given.

#### How to reproduce it (as minimally and precisely as possible):
See as described above.

#### Anything else we need to know?:
ETH Tx ID 0x5cfdb49a5303b7f71f9248a00b49b3bd0f353098a21b9d0f3ab930e812036f06
Defichain receiving address df1qs7uza0nxz9pq9tuwrh7dmslfkqs63aey7yeghv
Please advise how to proceed with recovery to recover my stuck funds, USDT 10400.

**Comment by Defianer** [comment]
Much appreciated, thank you! Looking forward to get my funds back!

**Comment by Defianer** [comment]
Hi Pierre,
any possibility that you could get this done on Monday?
With the current volatility in the market would much appreciate fast access to my funds to put it to work.
Many thanks & best regards!

**Comment by Defianer** [comment]
Funds stuck for more than 5 days, approaching 6 days in a few hours. Really appreciate if this can be resolved quickly, please.

**Comment by Defianer** [comment]
@pierregee 
As said, many thanks in advance. When can I expect this to progress, please?

**Comment by lykalabrada** [comment]
Hi @Defianer, your transaction has been completed
<img width="607" alt="image" src="https://github.com/BirthdayResearch/quantum-app/assets/17063281/fe655a0b-5f61-4c09-b5d9-26bccd89d2c3">

You might have accidentally entered an incorrect txn hash while trying to recover? As I was able to do it successfully using the hash you provided above:
![image](https://github.com/BirthdayResearch/quantum-app/assets/17063281/1c88918a-efdf-416d-9321-a63967f169a9)

**Comment by pierregee** [comment]
@lykalabrada @Defianer Yes, I have completed the flow and successfully transferred it. Here's the tx. Thank you!

https://defiscan.live/transactions/d7dd677860f151b6354ae3c946fa03b9c3062024f996028b57fc01e904aa411d
