### ISSUE TITLE
Unable to (resume) claim funds after bridging from DefiChain to Ethereum

### ISSUE THREAD

**Issue by kbingko** [BirthdayResearch/quantum-app#21]
#### How to reproduce it (as minimally and precisely as possible):
1) Initiated instant bridging process from Defichain to Ethereum with 0.1253 eth
2) Funds sent to specified defichain address at df1q85p4vumt7gwv4w0myefdslgnvzrjrkahnene9c
3) Waited allotted time for bridging process to finish and got to the claim step but button greyed out
4) Could not resume process after refresh of browser
5) Tried hours later with the same steps using the 'retry transfer' button when verifying funds in the defichain address at df1q85p4vumt7gwv4w0myefdslgnvzrjrkahnene9c an error 4 is returned
6) No way to get back to the claim step

#### Anything else we need to know?:
Please initiate the refund of funds to original wallet or allow claim process to go through to the target eth address

**Comment by kbingko** [comment]
/area/transactions

**Comment by pierregee** [comment]
We have verified it and refunded back the funds to your refund address. Thank you
