### ISSUE TITLE
Can't claim funds on ETH due to concurrent concurrent transaction by another user

### ISSUE THREAD

**Issue by SimonSuckut** [BirthdayResearch/quantum-app#22]
#### Transaction Data:
Here is the data for the failed Transaction: 
Amount Transfered: 1564 dUSDT
DFI Tx-ID: 095057985bc55ab0381aa9e49ad314d13b9de5ab93cb4f51f24f5d1cb311bfd4
Bridge deposit address: df1q7ew2g8xmgxqdfwnm6c79deyd0l5g9urjr638hn
DFI refund address: df1q64mudeus4v87ne0fvp5leugryj8tre9ncyz05a
Ethereum receiver address: 0xcDDcb484925f1aC2FeFa2D668ea501ae071A9F51

#### What happened:
I tried to transfer USDT from DeFiChain to Ethereum over a month ago. I send them to the deposit address on the DeFiChain side, but was not able to claim the funds on the Ethereum chain. The page froze when I tried to claim the funds with MetaMask. After a page reload I was not able to recover the transaction.  I exptected to get a refund on DeFiChain after 24 hours (which apparently is not the case). I already filled the google form - with no response so far.

As nothing happened I tried to track down where the funds went. What I found out is that apparently another user tried to use the bridge at the same time (only a few blocks offset to my transactions: deposit address: df1ql35lrce6x0p2g2vhyu6uledmjr4ah0ah6h9x9a, ETH-Claim transcation: 0x489f78d5783f8cee8e3292d2328037bda76170fa012483b2f836e427b77b6a7d).  After this transaction by another user the liquidity on ETH side was apparently not sufficient any more to satisfy my claiml which I suspect was the reason why I could not even start the clain transaction in metamask through the web-interface.

#### What you expected to happen:
Getting a refund after 24 hours

**Comment by pierregee** [comment]
We have verified it and the funds have been refunded. Thank you
