### ISSUE TITLE
wrong dtoken sent

### ISSUE THREAD

**Issue by happydayxxl** [BirthdayResearch/quantum-app#4]
Hello Birthday Reasearch Team!

I am used the QuantumBridge on the 29th Juni 2023 and sent the wrong dToken to the quantum DFI Adress. 
I wanted to swap dETH to ETH but i missed the pick of the right dToken.

Please help me out the dETH are on that address right now please contact me to talk with each other and maybe find any way to solve this.

best regards

**Comment by thedoublejay** [comment]
Hi @happydayxxl we need more details for this, would it be possible to the support form?https://forms.gle/4HcoTwonXuzwKRRB9

**Comment by happydayxxl** [comment]
I filled out the form thanks for your response

**Comment by thedoublejay** [comment]
@happydayxxl Should be done, please close the issue when verified

**Comment by happydayxxl** [comment]
THANK YOU SO MUCH
