### ISSUE TITLE
DfI did not transfer to MetaMask Wallet

### ISSUE THREAD

**Issue by ian309699** [BirthdayResearch/quantum-app#8]
#### What you expected to happen: 
I did the first part of the transfer with  no problem, but I was unable to claim the tokens, I might have waited too long to claim them if that is possible. When I did try and claim them, nothing would happen, the wallet would not automatically come on the screen. Then I hit the back button, and I cannot get back to the claim screen. Will the tokens be automatically put back in my DFI wallet?

#### Anything else we need to know?:
the DFI transaction Id# 7a448f0e6fccdfe3a9c2da77736eca047f4380ac6e04943d56d8a2fe68410917

**Comment by ian309699** [comment]
a little help? please

**Comment by lykalabrada** [comment]
Hi @ian309699, we're looking into this issue. You're right, the claim has expired and therefore no longer claimable, we will get back to you!

**Comment by ian309699** [comment]
Thank You

**Comment by lykalabrada** [comment]
We have refunded this transaction. 
Transaction Id: 6396f1a7acec99502dff4ecc7dc48c931a2b5d7795665c0316d9f005e549ef48

**Comment by ian309699** [comment]
Thank You
