### ISSUE TITLE
Error Code 3: DefiChain to Ethereum - Funds Inaccessible

### ISSUE THREAD

**Issue by TrePhoenix** [BirthdayResearch/quantum-app#9]
#### What happened:
I sent 0.44957649 dETH to the Quantum Bridge Wallet, but the Bridge expected 0.44957 . I get the same error when I click Try Again and there does not seem to be any way to change the dETH amount from 0.44957 to 0.44957649 on the Quantum Bridge Wallet. 0.44957649 came from the DeFiChain LiteWallet on Android when I clicked Maximum. If I click "X" to close the window, I get this warning: "You may lose any pending transaction and funds related to it. This is irrecoverable."

#### What you expected to happen:
I expected to receive 0.44957649 or 0.44957 ETH in MetaMask or the dETH refunded back to my LiteWallet when the bridege failed.

#### How to reproduce it (as minimally and precisely as possible):
Send a different amount than you enter in the Quantum Bridge app.

#### Anything else we need to know?:
This is my first time using the Quantum Bridge. Can the Bridge be coded to accept the same digits of precision as the LiteWallet?
I read the documentation and watched a tutorial video, but think there could be more warning in the UI to try to prevent this, especially since there no way to edit the amount and the funds are currently inaccessible.
What can I do at this point?
Tx ID: b1ef470879174546535f2f8dcd165d99007a163496991fa49629fa55b7a003ed
Thank you in advance!!

**Comment by TrePhoenix** [comment]
I haven't received any reply to this post so this is an FYI if someone else runs into this and finds it useful. After 2 weeks my dETH are back in my Litewallet, but I don't know if that happened automatically at some point or if someone acted on this post.

**Comment by pierregee** [comment]
Hi @TrePhoenix , this was refunded to you after the team has confirmed the transaction. We are aware of this issue regarding decimal points in Quantum. Will let the team know of a better way to handle this! Thank you

**Comment by TrePhoenix** [comment]
Thank you Pierre and Team!
